### PR TITLE
Autoscaling

### LINKED ISSUE #13: Autoscaling
Read about the different metrics you can check to scale your cluster.

1. Configure the kubernetes cluster to auto scale by `cpu` and `memory`, and give it a minimum and maximum pods.
2. Create a `custom` metric to scale by, which scale the deployment by the response time of the request.
You can see in insomnia the response time that took the request to return here:
Default_–_Dgraph_and_person_ts_—___exp0se_data-pipeline

We want to provide a fast experience to our users and don't want the response to took more then 2 second to return, so if it's more then 2 seconds (or 2000ms)  scale it up.

### PR DESCRIPTION
**Pull request by shahargalon**

### CODE REVIEW

**Comment by shahargalon** [comment]
@nirgn975 
I applied the HPA (horizontal pod autoscaler) and also vertical autoscaler (this is done via the GCP dashbord)  to scale by cpu.
regards the response time, this is more complicated, I think to do that after the prometheus stage, (to retrieve this metric and push it to drive-stack and then I will be able to use it on HPA)

what do thinks, should I merge it and move to the next task or keep investigate it?

**Review by nirgn975 — CHANGES_REQUESTED** [review]
@shahargalon Looking good. But 2 things:
1. Put a link to the issue.
2. Did you tried to stress test your cluster and see if it scale the deployment to more then 2 pods? Because I looked at the history graph, and it didn't look like you have did that..

**Comment by shahargalon** [comment]
@nirgn975 ,
yes I did that, (but only for the HPA ) I couldn't succeed to get a high performance to test the vertical auto scale (node scaling)

here is an example of the HPA on work

image

**Comment by nirgn975** [comment]
> @nirgn975 ,
> yes I did that, (but only for the HPA ) I couldn't succeed to get a high performance to test the vertical auto scale (node scaling)
> 
> here is an example of the HPA on work
> 
> image

Look likes you did it on your own machine, did you try to do it in the cloud?

**Comment by shahargalon** [comment]
@nirgn975 
this is from on the cloud.. I just showed you this from my machine..

**Review by nirgn975 — APPROVED** [review]

**Pull request merged**
